#### This is a program for calculating the spearman correlations between cytokine and metabolite abundances.

### load the libraries

```{r}
### load the libraries
library(tidyverse)
library(ComplexHeatmap)
library(circlize)
library(psych)
source("~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/R/cyt_met_correlation_functions.R")

```

### load the data

```r
load("~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/data/processed/all_cyt_met_standardized.RData")
```

## Separate T21 and D21 subjects

``` r
T21.mixed <- lapply(all_standardized, function(x) {
    x %>%
        filter(rownames(x) %in% (all_standardized$clinic %>% filter(Karyotype == "T21") %>% .$LabID))
})
D21.mixed <- lapply(all_standardized, function(x) {
    x %>%
        filter(rownames(x) %in% (all_standardized$clinic %>% filter(Karyotype == "Control") %>% .$LabID))
})


save(T21.mixed,file = "~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/data/processed/T21_standardized_cyt_met.RData")
save(D21.mixed,file= "~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/data/processed/D21_standardized_cyt_met.RData")

```

## Load the data in subsequent analyses

``` r
load("~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/data/processed/T21_standardized_cyt_met.RData")
load("~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/data/processed/D21_standardized_cyt_met.RData")
```

### Calculate the correlations within Cytokines

``` r
T21_cytokine_correlations <- T21.mixed$cytokines %>%
    corr.test(method = "spearman", adjust = "fdr")

D21_cytokine_correlations <- D21.mixed$cytokines %>%
    corr.test(method = "spearman", adjust = "fdr")

```

### Calculate the correlations within Metabolites

``` r
T21_metabolite_correlations <- T21.mixed$metabolites %>%
    corr.test(method = "spearman", adjust = "fdr")

D21_metabolite_correlations <- D21.mixed$metabolites %>%
    corr.test(method = "spearman", adjust = "fdr")

```

### Heatmaps

``` r
cyt_heatmap = Heatmap(T21_cytokine_correlations$
	r, 
	name = "rho",
	row_dend_reorder = TRUE, 
	column_dend_reorder = TRUE, 
	show_row_dend = FALSE, 
	show_column_dend = TRUE, 
	column_names_gp = gpar(fontsize = 7),
	row_names_gp = gpar(fontsize =6 ), 
	show_row_names = TRUE, 
	show_column_names = FALSE,
	column_split = 4,
	row_split = 4,
	row_title = NULL,
	column_title = NULL,
	col=colorRamp2(c(-.5, 0, .5), c("blue", "white", "red")),
	heatmap_legend_param = list(direction = "horizontal",labels_gp = gpar(fontsize = 6), legend_title_gp = gpar(fontsize = 7)),
    height = nrow(T21_cytokine_correlations$r) *unit(2,"mm"),
    column_dend_height = unit(4,"mm")
    )
pdf("~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/results/correlation_heatmaps/T21_Cytokines_Correlation_Heatmap.pdf", height = 5, width =3)
draw(cyt_heatmap)
dev.off()

```

``` r
met_heatmap = Heatmap(T21_metabolite_correlations$r, 
	name = "correlation coefficient",
	row_dend_reorder = TRUE, 
	column_dend_reorder = TRUE, 
	show_row_dend = FALSE, 
	show_column_dend = TRUE, 
	column_names_gp = gpar(fontsize = 3),
	row_names_gp = gpar(fontsize = 3), 
	show_row_names = TRUE, 
	show_column_names =FALSE,
	column_split = 4,
    row_title = NULL,
	row_split = 4,
	column_title = NULL,
	col=colorRamp2(c(-.5, 0, .5), c("blue", "white", "red")),
	heatmap_legend_param = list(direction = "horizontal")
    )
pdf("~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/results/correlation_heatmaps/T21_Metabolites_Correlation_Heatmap.pdf")
draw(met_heatmap, heatmap_legend_side = "bottom")
dev.off()

```

### Calculate the correlations across molecular classs

``` r
T21.omics <- cbind( T21.mixed$cytokines, T21.mixed$metabolites)

T21_correlations <- T21.omics %>%
    corr.test(method = "spearman", adjust = "fdr")

D21.omics <- cbind( D21.mixed$cytokines,D21.mixed$metabolites)

D21_correlations <- D21.omics %>%
    corr.test(method = "spearman", adjust = "fdr")
```


### Heatmap of multiomic correlations

``` r
all_heatmap = Heatmap(T21_correlations$r, 
	name = "correlation coefficient",
	row_dend_reorder = TRUE, 
	column_dend_reorder = TRUE, 
	show_row_dend = FALSE, 
	show_column_dend = TRUE, 
	column_names_gp = gpar(fontsize = 3),
	row_names_gp = gpar(fontsize = 2), 
	show_row_names = TRUE, 
	show_column_names =FALSE,
	column_split = 4,
    row_title = NULL,
	row_split = 4,
	column_title = NULL,
	col=colorRamp2(c(-.5, 0, .5), c("blue", "white", "red")),
	heatmap_legend_param = list(direction = "horizontal")
    )
pdf("~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/results/correlation_heatmaps/T21_ALL_Correlation_Heatmap.pdf")
draw(all_heatmap, heatmap_legend_side = "bottom")
dev.off()

```



### Cytokine-metabolite scatter plots

#### Convert data to long format

``` r

T21_cytokine_correlations <- LongCorr(T21_cytokine_correlations)
T21_metabolite_correlations <- LongCorr(T21_metabolite_correlations)
T21_correlations <- LongCorr(T21_correlations)

T21_correlations$long <- T21_correlations$long %>%
    filter(A %in% names(T21.mixed$cytokines) & B %in% names(T21.mixed$metabolites))

```

#### Plot creation
```r
corrScatterPlotsSingle(psych_object = T21_cytokine_correlations,
                       molecule_class = "cytokines",
                       omics_data = T21.mixed)


corrScatterPlotsSingle(psych_object = T21_metabolite_correlations,
                       molecule_class = "metabolites",
                       omics_data = T21.mixed)



corrScatterPlotsMultiple(psych_object = T21_correlations,
                       molecule_classes = c("cytokines","metabolites"),
                       omics_data = T21.mixed)					   
```


### Compare T21 and D21 Correlations

```r
library(ggrepel)
D21_correlations <- LongCorr(D21_correlations)
D21_correlations$long <- D21_correlations$long %>%
    filter(A %in% names(D21.mixed$cytokines) & B %in% names(D21.mixed$metabolites))

T21_correlations$long %>%
    filter(fdr < .1)

D21_correlations$long %>%
    filter(fdr < .1)

write.csv(T21_correlations$long, file = "~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/results/tables/T21_cyt_met_correlations.csv", row.names = F)
write.csv(D21_correlations$long, file = "~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/results/tables/D21_cyt_met_correlations.csv", row.names = F)

```

```r


all_correlations <- T21_correlations$long %>%
    full_join(D21_correlations$long, by = c("A","B"))

names(all_correlations) <- c("cytokine", "metabolite", "T21_r", "T21_fdr", "D21_r", "D21_fdr")

all_correlations$significance <- ifelse(all_correlations$T21_fdr < .1 & all_correlations$D21_fdr < .1, "Both",
                                 ifelse(all_correlations$T21_fdr < .1 & all_correlations$D21_fdr > .1, "T21 only",
                                        ifelse(all_correlations$T21_fdr > .1 & all_correlations$D21_fdr < .1, "D21 only", "None")))

all_correlations$diff <- abs(all_correlations$T21_r - all_correlations$D21_r)

all_correlations$label <- ifelse(abs(all_correlations$T21_r) > .25 & abs(all_correlations$D21_r) < .15, paste(all_correlations$cytokine, "-",all_correlations$metabolite),
                               ifelse(abs(all_correlations$T21_r) < .1 & abs(all_correlations$D21_r) > .5, paste(all_correlations$cytokine, "-",all_correlations$metabolite) ,""))
p1 <- ggplot(all_correlations, aes(x = T21_r, y = D21_r, color = significance,label = label, alpha = significance ))+
    geom_point(size = 2) +
    geom_label_repel(max.overlaps = 1e6, size = 2)+
    theme_classic() +
    theme(legend.position = "bottom") +
    xlim(-.6,.6) + ylim(-.6,.6) +
    geom_vline(xintercept = 0, linetype = "dashed", color = "grey") +
    geom_hline(yintercept = 0, linetype = "dashed", color = "grey") +
    scale_color_manual(values = c("Both" = "red", "T21 only" = "blue", "D21 only" = "brown", "None" = "gray"))+
    scale_alpha_manual(values = c(1,1,.2,1))  +
    xlab("T21 correlation coefficient") +
    ylab("D21 correlation coefficient")
pdf("~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/results/correlation_scatter_plots/karyotype/T21_D21_correlation_scatter.pdf")
print(p1)
dev.off()

```



## Case Imbalance
To test whether the case imbalance between the D21 and T21 data is enough to affect the correlations, I will subsample the T21 data to 46 (the same size at the D21 cohort) and recalculate the correlations. 

```r
library(parallel)

sub_corr <- mclapply(1:1000, function(x) {
    print(x)
    to_keep <- sample(1:nrow(T21.omics), 46)
    tmp.omics <- T21.omics[to_keep,]
    tmp_correlations <- tmp.omics %>%
        corr.test(method = "spearman", adjust = "fdr")
    tmp_correlations <- LongCorr(tmp_correlations)
    tmp_correlations$long <- tmp_correlations$long %>%
        filter(A %in% names(T21.mixed$cytokines) & B %in% names(T21.mixed$metabolites))
    return(tmp_correlations$long)
}, mc.cores = 6)

save(sub_corr, file = "~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/results/sub_corr.RData")

sub_corr <- lapply(sub_corr, function(x) {
    x %>%
        select(A,B,r)
})

library(purrr)

sub_corr <- sub_corr %>%
    reduce(left_join, by = c("A", "B"))


avg_r <- sub_corr %>%
    mutate(avg_r = rowMeans(pick(where(is.numeric)))) %>%
    select(A,B,avg_r)
              

all_correlations <- D21_correlations$long %>%
    left_join(avg_r, by = c('A', 'B')) %>%
    mutate(diff = avg_r -r) %>%
    arrange(-diff) %>%
    mutate(rank = row_number())
names(all_correlations)[c(3,5)] <- c("D21", "T21_average")

all_correlations %>%
    summarise(correlation = cor(D21,T21_average, method = "spearman"))


all_correlations <- all_correlations %>%
    select(A,B,T21_average,D21,rank) %>%
    pivot_longer(cols = -c('A','B','rank'))
names(all_correlations)[4] <- "karyotype"

p1 <- ggplot(all_correlations, aes(x = rank, y = value, color = karyotype)) +
    geom_point(alpha = .3) +
    theme_classic() +
    xlab("") +
    ylab("correlation coefficient") +
    theme(axis.ticks.x = element_line(linewidth = 0),
          axis.text.x = element_text(size = 0),
          legend.position = "bottom")+
    ylim(c(-.6,.6))
pdf("~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/results/correlation_diff_karytotype_plots/T21_vs_D21_corr_line_plots.pdf", width = 8, height = 4)
print(p1)
dev.off()



```


### Metabolite Pathway enrichment

```r
load("~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/data/pathway/metabolite_pathway.RData")


correlations_long <- T21_correlations$long


T21_enrichment <- correlationsEnrichmentWrapper(T21_correlations$long,met_path)

enrich_plot_data <- enrichmentPlotPrep(T21_enrichment)

p1 <- ggplot(enrich_plot_data, aes(x = cytokine, y = pathway, fill = avg_corr, size = -log10(fdr))) +
    geom_point(shape = 21) +
    scale_fill_continuous(type = "viridis") +
    theme_classic() +
    theme(legend.position = "bottom",
          axis.text.x = element_text(angle = 60,hjust = 1, size = 12),
          axis.text.y = element_text(size = 12),
          axis.title = element_text(size = 14)
          )

pdf("~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/results/enrichment/T21_enrichment.pdf")
print(p1)
dev.off()
```


## Comparing enrichments between karyotypes

```r

D21_enrichment <- correlationsEnrichmentWrapper(D21_correlations$long,met_path)

D21_enrich_plot_data <- enrichmentPlotPrep(D21_enrichment)
```

