---
title: "Pathway Annotation"
author: "Lucas Gillenwater"
date: "`r Sys.Date()`"
output: html_document
---
For downstream enrichment analyses, we annotated features based on prior knowledge of biological pathways. 

# Necessary Libraries
```{r}
library(openxlsx)
```
# Load the molecular data and pathway data

```{r}
load("~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/data/processed/T21_mixed_cyt_met.Rdata")
met_path <- read.xlsx("~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/data/pathway/HTP_P4C_metabolites_original_annotation(10212) copy.xlsx")
```

## Align IDs

```r

library(fuzzyjoin)
library(tidyverse)
library(stringdist)
metsA <- data.frame(met = names(T21.mixed$metabolites)) 
metsB <- data.frame(met = met_path$compound)


met_map <- stringdist_left_join(metsA, metsB,by = "met", distance_col = "dist")%>%
    group_by(met.x) %>%
    filter(dist < 1) %>%
    as.data.frame()


no_match <- which(is.na(match(metsA$met, met_map$met.x)))
no_match <- metsA$met[no_match]

map_to <-which(grepl(no_match[1], metsB$met, ignore.case = T))
met_map[nrow(met_map)+1 ,1:2] <- c(no_match[1], metsB$met[map_to])

dist_to <- sapply(metsB$met, function(x) stringdist(no_match[2],x))
map_to <- which(dist_to == min(dist_to))

met_map[nrow(met_map)+1 ,1:2] <- c(no_match[2], metsB$met[map_to])


met_path <- met_path %>%
    full_join(met_map, by = c("compound" = "met.y"))
names(met_path)[7] <- "name"

save(met_path, file = "~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/data/pathway/metabolite_pathway.RData")
```
