# Clustering of T21 subjects

## Load required scripts and packages
```r
source("~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/R/data_prep_functions.R")
source("~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/R/nemo_functions.R")
source("~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/R/cluster_evaluation.R")
library(tidyverse)
```

## Set the seed for reproducibility

``` r
set.seed(1234)
```

## Load the data
```r
load("~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/data/processed/T21_standardized_cyt_met.RData")
load("~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/data/processed/processed_transcriptome.RData")
```

## Steps in clustering as defined by Milligan(1996)

1. Selection of objects and variables - overlap of cyt, met, RNA data (protein coding with some variance) (001_Data_Processing.Rmd, data_prep_functions.R)
2. Decisions concerning variable normalization - adjustment for age, sex, and sample_source, standardized (001_Data_Processing.Rmd, data_prep_functions.R)
3. Selection of a distance measure - NEMO ( 006_clustering.Rmd,nemo_functions.R)
4. Selection of a clustering method - spectral clustering ( 006_clustering.Rmd,nemo_functions.R)
5. Determining the numeber of clusters - eigengap, rotation cost, NEMO modified eigengap (eigengap * num_clusters)(006_clustering.Rmd, cluster_evaluation.R)
6. Validating the clusters - bootstrapping, 1000 iterations (006_clustering.Rmd, cluster_evaluation.R)
7. Descibing and profiling the clusters - (007_cluster_profile.Rmd, cluster_evaluation.R) 


## Metrics for determining the number of clusters
1. Eigengap
	* 
2. Robust Clust
   *
3. Davies-Bouldin
   * Lower index values indicate a better clustering result. The index is improved (lowered) by increased separation between clusters and decreased variation within clusters.
4. Calinksi-Harabasz
   * A higher value of CH indicates a better clustering, because it means that the data points are more spread out between clusters than they are within clusters.

## Determining the number of clusters based on the number of overlaps between two co-occurring conditions


An  approach may consider that we are interested in finding axes of disease co-occurance among the data. Therefore, we will restrict our number of neighbors to the mean number of neighbors. 

The number of clusters with the best overall score is 4, with this number of neighbors. 

```r
diff_sig_threshold = .1
clinical_threshold = .2
omics.list = list(t(T21.mixed$cytokines),t(T21.mixed$metabolites))
NUMC <- 2:6
phenotypes =  names(T21.mixed$clinic)[c(2,6,9:21)]
iterations = 100

## condition_counts <- T21.mixed$clinic %>%
##     dplyr::select(phenotypes) %>%
##     dplyr::select(-c(Sex, Age_at_visit)) %>%
##     reframe(count = colSums(., na.rm = T)) 
## num_neighbors <- median(condition_counts$count)

## overlap <- sapply(phenotypes[3:length(phenotypes)], function(x) {
##     sapply(phenotypes[3:length(phenotypes)], function(y) {
##         tmp <- table(T21.mixed$clinic[[x]],T21.mixed$clinic[[y]])
##         return(tmp["1","1"])
##     })})
## num_neighbors = floor(mean(overlap[upper.tri(overlap)]))

num_neighbors = 25
res <- clusterEval(omics.list = list(t(T21.mixed$cytokines),t(T21.mixed$metabolites)),
                clinic = T21.mixed$clinic,
                phenotypes = phenotypes,
                NUMC = NUMC,  
                diff_sig_threshold = diff_sig_threshold,
                clinical_threshold = clinical_threshold,
                num_neighbors = num_neighbors,
                iterations = iterations)
res$summary
res$eigengap
res$nemo
write_csv(x = res$summary,file = "~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/results/tables/cyt_met_clustering_results.csv")


cytokine_res = clusterEval(omics.list = list(t(T21.mixed$cytokines)),
						clinic = T21.mixed$clinic,
					 	phenotypes = phenotypes,
					  	iterations = iterations, 
						NUMC = NUMC,  
                      diff_sig_threshold = diff_sig_threshold,
                      clinical_threshold = clinical_threshold,
                      num_neighbors = num_neighbors)
cytokine_res$summary
cytokine_res$eigengap
cytokine_res$nemo
write_csv(x = cytokine_res$summary,file = "~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/results/tables/cytokine_clustering_results.csv")

metabolite_res = clusterEval(omics.list = list(t(T21.mixed$metabolites)),
						clinic = T21.mixed$clinic,
					 	phenotypes = phenotypes,
					  	iterations = iterations, 
						NUMC = 2:5,  
                      diff_sig_threshold = diff_sig_threshold ,
                      clinical_threshold = clinical_threshold,
                      num_neighbors = num_neighbors)
metabolite_res$summary
metabolite_res$eigengap
metabolite_res$nemo
write_csv(x = metabolite_res$summary,file = "~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/results/tables/metabolite_clustering_results.csv")
```

## Perform the clustering

``` r

all_clust <- nemo.clustering(omics.list = list(t(T21.mixed$cytokines),t(T21.mixed$metabolites)),num.clusters = 4,num.neighbors = num_neighbors)
save(all_clust, file ="~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/results/clusterings/all_clust.RData")

cyt_clust <- nemo.clustering(omics.list = list(t(T21.mixed$cytokines)),num.clusters =2,num.neighbors = num_neighbors)
save(cyt_clust, file ="~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/results/clusterings/cyt_clust.RData")

met_clust <- nemo.clustering(omics.list = list(t(T21.mixed$metabolites)),num.clusters = 3,num.neighbors = num_neighbors)
save(met_clust, file ="~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/results/clusterings/cyt_clust.RData")

```


## How stable are the clusters over the number of neighbors?

```r

diff_sig_threshold = .1
clinical_threshold = .2
omics.list = list(t(T21.mixed$cytokines),t(T21.mixed$metabolites))
NUMC <- 2:6
phenotypes =  names(T21.mixed$clinic)[c(2,6,9:21)]
iterations = 1


num_neighbors_grid <- seq(10,100,5)

multi_omic_res = lapply(num_neighbors_grid, function(x) {
    print(x)
    clusterEval(omics.list = list(t(T21.mixed$cytokines),t(T21.mixed$metabolites)),
                clinic = T21.mixed$clinic,
                phenotypes = phenotypes,
                iterations = iterations,
                NUMC = NUMC,  
                diff_sig_threshold = diff_sig_threshold,
                clinical_threshold = clinical_threshold,
                num_neighbors = x)
})

names(multi_omic_res) <- num_neighbors_grid

enriched_conditions <- sapply(multi_omic_res, function(x) x$summary$`# of enriched conditions`)
enriched_conditions <- as.data.frame(enriched_conditions)
enriched_conditions$clusters <- NUMC

enriched_conditions <- enriched_conditions %>%
    pivot_longer(cols = -clusters)

ggplot(enriched_conditions, aes(x = clusters, y = value, color = as.factor(name))) +
    geom_line() +
    theme_classic() +
    ylab("# of enriched features") + xlab("# of clusters")


nemo <- as.data.frame(sapply(multi_omic_res, function(x) x$nemo)) %>%
    as.data.frame() %>%
    rownames_to_column("neighbors")
names(nemo)[2] <- "nemo"

plot(nemo$neighbors, nemo$nemo)
lines(nemo$neighbors, nemo$nemo)



lapply(multi_omic_res[1:4], function(x) x$summary)
lapply(multi_omic_res[1:4], function(x) x$eigen)


```
